sudo: required
services:
- docker
language: bash
env:
  matrix:
  - ARCH=arm

addons:
   apt:
      packages:
      - lxc

script:
  - lxc-create -t ubuntu -n armbuntu -- -a armhf
  - ./travis-build.sh
  - >
    if [ -n "$TRAVIS_TAG" ]; then
      # push image
      travis_retry timeout 5m docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      ./travis-deploy.sh
    fi
