sudo: required
services:
- docker
language: bash
env:
  matrix:
  - ARCH=arm

script:
  - ./travis-build.sh
  - >
    travis_retry timeout 5m docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    if [ -n "$TRAVIS_TAG" ]; then
      ./travis-deploy.sh $TRAVIS_TAG
    else 
      ./travis-deploy.sh
    fi
