sudo: required
services:
- docker
language: bash
env:
- RFID_MUSICPLAYER=0.4.0
script:
# prepare for cross compiling
- ./prepare_local_build_env.sh
## build rfid reader image
- docker build --build-arg RFID_MUSICPLAYER=$RFID_MUSICPLAYER -f Dockerfile.rfid_reader -t protenhan/rpi-rfid-musicplayer_reader .
## build the main player
- docker build --build-arg RFID_MUSICPLAYER=$RFID_MUSICPLAYER -f Dockerfile.player -t protenhan/rpi-rfid-musicplayer_player .
## build the button controler
- docker build --build-arg RFID_MUSICPLAYER=$RFID_MUSICPLAYER -f Dockerfile.button_control -t protenhan/rpi-rfid-musicplayer_control .
## push the player image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then  docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker tag $DOCKER_USER/rpi-rfid-musicplayer_player $DOCKER_USER/rpi-rfid-musicplayer_player:$RFID_MUSICPLAYER
    docker push $DOCKER_USER/rpi-rfid-musicplayer_player:$RFID_MUSICPLAYER
    docker push $DOCKER_USER/rpi-rfid-musicplayer_player
  fi
## push rfid reader image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then  docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker tag $DOCKER_USER/rpi-rfid-musicplayer_reader $DOCKER_USER/rpi-rfid-musicplayer_reader:$RFID_MUSICPLAYER-alpine
    docker push $DOCKER_USER/rpi-rfid-musicplayer_reader:$RFID_MUSICPLAYER-alpine
    docker push $DOCKER_USER/rpi-rfid-musicplayer_reader
  fi
## push control  image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then  docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker tag $DOCKER_USER/rpi-rfid-musicplayer_control $DOCKER_USER/rpi-rfid-musicplayer_control:$RFID_MUSICPLAYER-alpine
    docker push $DOCKER_USER/rpi-rfid-musicplayer_control:$RFID_MUSICPLAYER-alpine
    docker push $DOCKER_USER/rpi-rfid-musicplayer_control
  fi