FROM golang:1.11.2-alpine3.8 as builder

WORKDIR /go/src/app
COPY ./src/go .

RUN apk update && apk add git
RUN go get -d -v ./...
RUN env GOOS=linux GOARCH=arm GOARM=7 go build -o rpi-rfid-musicplayer_player

FROM scratch

COPY --from=builder /go/src/app/rpi-rfid-musicplayer_player /rpi-rfid-musicplayer_player
EXPOSE 8000
CMD [ "rpi-rfid-musicplayer_player" ]

