FROM arm32v6/alpine:3.8
LABEL maintainer="@protenhan"

COPY qemu-arm-static /usr/bin/
RUN apk update &&\
    apk -U add \
        python3 \
        linux-headers \
        python3-dev \
        gcc \
        musl-dev 

# Setup for the project
COPY src/button_control/python /button_control/
RUN pip3 install -r /button_control/requirements.txt

CMD ["python3","-u","/button_control/button_control.py"]
