FROM arm32v6/alpine:3.8
LABEL maintainer="@protenhan"

COPY qemu-arm-static /usr/bin/
RUN apk update &&\
    apk -U add \
        python3 \
        linux-headers \
        python3-dev \
        gcc \
        musl-dev 

# Setup for the project
COPY src/python/rfid_reader /rfid-musicplayer/
RUN pip3 install -r /rfid-musicplayer/requirements.txt

CMD ["python3","-u","/rfid-musicplayer/rfid_reader.py"]
